name: "git-config-from-token"
author: "Marco Ieni"
description: "Configure the git user corresponding to the `GITHUB_TOKEN` environment variable."
branding:
  icon: "zap"
  color: "yellow"
outputs:
  name:
    description: "Git author name"
    value: ${{ steps.git-author.outputs.name }}
  email:
    description: "Git author email"
    value: ${{ steps.git-author.outputs.email }}
runs:
  using: "composite"
  steps:
    - id: git-author
      name: Determine Git user info from GitHub token
      shell: bash
      run: |
        RELEASE_PLZ_TOKEN=${{ secrets.RELEASE_PLZ_TOKEN }}
        if [ -z "${RELEASE_PLZ_TOKEN+x}" ]; then
          echo "Error: environment variable GITHUB_TOKEN is undefined"
          exit 1
        fi

        if [ -z "$RELEASE_PLZ_TOKEN" ]; then
          echo "Error: environment variable GITHUB_TOKEN is empty"
          exit 1
        fi

        # The environment variable GITHUB_TOKEN is read by the `gh` cli
        RESPONSE=$(curl -H "Authorization: token ${RELEASE_PLZ_TOKEN}" ${FORGEJO_API_URL}/user)
        

        # Set the variable USER_NAME to the value of VIEWER_NAME if VIEWER_NAME is set and not null.
        # Otherwise, set USER_NAME to the value of VIEWER_LOGIN.
        USER_NAME=$(echo "$RESPONSE" | jq -r '.full_name // .login')
        USER_EMAIL=$(echo "$RESPONSE" | jq -r '.email // empty')

        git config --global user.name "$USER_NAME"
        git config --global user.email "$USER_EMAIL"

        echo "name=${USER_NAME}" >> "${GITHUB_OUTPUT}"
        echo "email=${USER_EMAIL}" >> "${GITHUB_OUTPUT}"
